## A "Hello World" Example of Machine Learning - Revisit

Loading the Iris dataset from scikit-learn. 

The first column represents Sepal length, the second column represents Sepal width,  the third column represents the petal length, and the fourth column the petal width of the flower samples. The classes (type of species) are already converted to integer labels where 0=Iris-Setosa, 1=Iris-Versicolor, 2=Iris-Virginica.

Here, we are using only two features: the third and fourth columns. 

In [15]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
X = iris.data[:, [0,1,2,3]]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
y = iris.target

In [18]:
print('Class labels:', np.unique(y))

Class labels: [0 1 2]


Scikit-learn algorithms support multi-class classification via the One-Versus-Rest(OvR) method. 

Splitting data into 70% training and 30% test data:

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1, stratify=y)

In [20]:
print('Labels counts in y:', np.bincount(y))
print('Labels counts in y_train:', np.bincount(y_train))
print('Labels counts in y_test:', np.bincount(y_test))

Labels counts in y: [50 50 50]
Labels counts in y_train: [35 35 35]
Labels counts in y_test: [15 15 15]


### Standardizing the features:

In [22]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler() #center the distribution around zero (mean), with a standard deviation of 1.
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
for x in range(0, len(X_train)):
    print(X_train[x])
    print(X_train_std[x])

[5.5 4.2 1.4 0.2]
[-0.4301064   2.63118533 -1.33269725 -1.30728421]
[5.4 3.4 1.7 0.2]
[-0.55053619  0.76918392 -1.16537974 -1.30728421]
[6.4 3.2 5.3 2.3]
[0.65376173 0.30368356 0.84243039 1.44587881]
[6.7 3.3 5.7 2.1]
[1.0150511  0.53643374 1.0655204  1.18367281]
[5.  3.2 1.2 0.2]
[-1.03225536  0.30368356 -1.44424226 -1.30728421]
[6.7 3.1 5.6 2.4]
[1.0150511  0.07093339 1.0097479  1.57698181]
[7.6 3.  6.6 2.1]
[ 2.09891923 -0.16181679  1.56747294  1.18367281]
[5.8 4.  1.2 0.2]
[-0.06881702  2.16568498 -1.44424226 -1.30728421]
[7.2 3.  5.8 1.6]
[ 1.61720006 -0.16181679  1.12129291  0.5281578 ]
[6.6 2.9 4.6 1.3]
[ 0.89462131 -0.39456697  0.45202286  0.1348488 ]
[5.  2.3 3.3 1. ]
[-1.03225536 -1.79106803 -0.27301968 -0.2584602 ]
[5.2 2.7 3.9 1.4]
[-0.79139578 -0.86006732  0.06161534  0.2659518 ]
[4.7 3.2 1.3 0.2]
[-1.39354474  0.30368356 -1.38846976 -1.30728421]
[6.1 2.8 4.7 1.2]
[ 0.29247235 -0.62731714  0.50779537  0.0037458 ]
[5.5 2.5 4.  1.3]
[-0.4301064  -1.32556767  0.11738784  0.13

In [23]:
from sklearn.linear_model import Perceptron

ppn = Perceptron(max_iter=100, eta0=0.1, random_state=42)
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=100, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=42, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

### Test the model with the hold-out test set

In [24]:
y_pred = ppn.predict(X_test_std)
print('Misclassified samples: ' + str((y_test != y_pred).sum()))

Misclassified samples: 3


In [25]:
from sklearn.metrics import accuracy_score

print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

Accuracy: 0.9333333333333333


In [26]:
X_new = [[1.4, 0.2, .2, 1.4]]
y_new = ppn.predict(X_new)
y_new

array([2])

### Evaluate the model using cross validation

In [32]:
from sklearn.model_selection import cross_val_score
cross_val_score(ppn, X_train_std, y_train, cv=4, scoring="accuracy")

array([0.92592593, 0.85185185, 0.66666667, 0.79166667])

### Exercise 1: What if we use all four features to train the model? Are the results better? Why? 

Since this model is supposed to be linearly separable it is better to have two data values that have a tread of classifying it. Too much data only complicates the model. 

### Exercise 2: Try with the scikit-learn stochastic gradient descent model instead of perceptron. Evaluate with cross-validation how does the model perform in terms of accuracy using both two features and four features. 

In [43]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(random_state=42)

In [44]:
sgd.fit(X_train_std, y_train)

y_pred = sgd.predict(X_test_std)
print('Misclassified samples: ' + str((y_test != y_pred).sum()))


print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

# X_new = [[4.6, 3.1]]
# y_new = sgd.predict(X_new)
# y_new
# X

Misclassified samples: 5
Accuracy: 0.8888888888888888


I got .93 with two features and .88 with four